name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      INTERNAL_PKG_KEY: ${{ secrets.INTERNAL_PKG_KEY }}
    steps:
      - uses: actions/checkout@v2
      
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: src\OWML.Launcher\OWML.Manifest.json
          prop_path: version
      - name: set version - EnableDebugMode
        uses: jossef/action-set-json-field@v1
        with:
          file: src\SampleMods\OWML.EnableDebugMode\manifest.json
          field: version
          value: ${{ steps.version.outputs.prop }}
      - name: set version - LoadCustomAssets
        uses: jossef/action-set-json-field@v1
        with:
          file: src\SampleMods\OWML.LoadCustomAssets\manifest.json
          field: version
          value: ${{ steps.version.outputs.prop }}
          
      - run: type src\OWML.ModHelper\Properties\AssemblyInfo.cs # todo
        
      - name: set csproj version
        uses: rshillington/file-content-replacer@master
        with:
          files: "**/AssemblyInfo.cs"
          from: '\[assembly: AssemblyVersion\(".*"\)\]'
          to: '[assembly: AssemblyVersion("${{ steps.version.outputs.prop }}")]'
      
      - run: type src\OWML.ModHelper\Properties\AssemblyInfo.cs # todo
      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
      - name: restore packages
        run: nuget restore OWML.sln
      - name: build
        run: msbuild OWML.sln
        
      - name: pack
        run: nuget pack src\OWML.ModHelper\OWML.ModHelper.csproj
      - uses: actions/upload-artifact@v2
        with:
          name: owml-nuget
          path: OWML.*.nupkg
      
      - name: zip
        run: |
          cd src\OWML.Launcher\bin\Debug
          mkdir Logs
          mkdir Mods
          7z a OWML.zip *
      - uses: actions/upload-artifact@v2
        with:
          name: owml-zip
          path: src\OWML.Launcher\bin\Debug\OWML.zip

  nuget:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        name: download artifact
        with:
          name: owml-nuget
      - uses: myci-actions/publish-nuget@2 # todo untested
        with:
          filename: OWML.*.nupkg
          api-key: ${{ secrets.NUGET_KEY }}
          
  release:
    runs-on: ubuntu-latest
    needs: nuget
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/download-artifact@v2
        name: download artifact
        with:
          name: owml-zip
      #todo create github release
